---
- name: "installing rspamd required packages"
  apt:
    name: "{{ package }}"
    state: present
  loop: "{{ rspamd_repo_dep }}"
  loop_control:
    loop_var: package
  when: rspamd_repo_state

- name: "importing rspamd gpg key"
  apt_key:
    state: present
    keyring: /etc/apt/trusted.gpg.d/rspamd.gpg
    url: "{{ rspamd_repo_key }}"
  when: rspamd_repo_state

- name: "add rspamd repository"
  template:
    src: "repository-debian.j2"
    dest: /etc/apt/sources.list.d/rspamd.list
    owner: root
    group: root
    mode: 0644
  when: rspamd_repo_state
  register: rspamd_repo_changed

- name: "update debian repository cache"
  apt:
    update_cache: true
  when: rspamd_repo_changed.changed

- name: "remove nginx repository"
  file:
    path: /etc/apt/sources.list.d/rspamd.list
    state: absent
  when: not rspamd_repo_state
