---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos-7
    image: centos:7
  - name: debian-10
    image: debian:10
  - name: ubuntu-1804
    image: ubuntu:18.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: github
verifier:
  name: testinfra
  lint:
    name: flake8
